language: ruby
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install: gem install bundler
env: SUITE="rspec"
script: bundle exec $SUITE
matrix:
  fast_finish: true
  include:
    - rvm: 2.5
      env: SUITE="rubocop"
  allow_failures:
    - rvm: ruby-head
